config/routes.rb
  Rails.application.routes.draw do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    root :to => 'home#index'
    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    resources :preloadsources
    resources :sourcetypes
    resources :languages
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<body>

    <!-- MAIN PAGE -->

    <!-- LANDING PAGE SETUP -->

    <div class="container" id="frontPage">
        <div class="row">
            <div id="frontPageTitle" class="col-xs-offset-2 col-xs-8">
                <h1><span id="frontPageLogo"><%= image_tag "feedmelingosrssmainlogo.png" %></span>FeedMeLingos
                </h1>
                <p>Learning a second language?<br/>Read, watch and listen to real, up-to-the-minute content, right here, right now!</p>
            </div>
        </div>
        <div class="row">
            <div id="clickflagprompt" class="col-xs-2">Click on a flag >></div>
            <div id="frontPageFlags" class="col-xs-8">
                <% Language.find_each do |language| %>
                <span><%= link_to image_tag("#{language.flagurl}", class: "flag"), language_path(language.id) %></span>
                <% end %>
            </div>
        </div>
        <div class="row">
            <div id="frontPageButton" style="text-align: center">
                <% if !current_user %>
                    <button type="button" class="btn btn-lg btn-primary" onclick="borderFlash();">Try it out as a guest</button>
                <% else %>
                    <p id="memberClickPrompt">Click on one of the flags above to explore the language pages.</p>
                <% end %>
            </div>
        </div>
    </div>

    <!-- End of Landing Page Setup -->

    

    <!-- EVENT SCRIPTS -->

    <!-- Site's own JavaScript file -->

<!-- FOOTER -->
    <!-- NB: always present! -->
    <div class="footer">
        <div class="container">
            <p>Website design &copy; PMM Web Development. Contains content from <a href="http">Twitter</a>. This site is intended as a free educational aid.</p>
        </div>
    </div>
<!-- End of Footer -->

</body>