config/routes.rb
  Rails.application.routes.draw do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    root :to => 'home#index'
    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    resources :preloadsources
    resources :sourcetypes
    resources :languages
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/sourcetypes_controller.rb
class SourcetypesController < ApplicationController
  before_action :set_sourcetype, only: [:show, :edit, :update, :destroy]

  # GET /sourcetypes
  # GET /sourcetypes.json
  def index
    @sourcetypes = Sourcetype.all
  end

  # GET /sourcetypes/1
  # GET /sourcetypes/1.json
  def show
  end

  # GET /sourcetypes/new
  def new
    @sourcetype = Sourcetype.new
  end

  # GET /sourcetypes/1/edit
  def edit
  end

  # POST /sourcetypes
  # POST /sourcetypes.json
  def create
    @sourcetype = Sourcetype.new(sourcetype_params)

    respond_to do |format|
      if @sourcetype.save
        format.html { redirect_to @sourcetype, notice: 'Sourcetype was successfully created.' }
        format.json { render :show, status: :created, location: @sourcetype }
      else
        format.html { render :new }
        format.json { render json: @sourcetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sourcetypes/1
  # PATCH/PUT /sourcetypes/1.json
  def update
    respond_to do |format|
      if @sourcetype.update(sourcetype_params)
        format.html { redirect_to @sourcetype, notice: 'Sourcetype was successfully updated.' }
        format.json { render :show, status: :ok, location: @sourcetype }
      else
        format.html { render :edit }
        format.json { render json: @sourcetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sourcetypes/1
  # DELETE /sourcetypes/1.json
  def destroy
    @sourcetype.destroy
    respond_to do |format|
      format.html { redirect_to sourcetypes_url, notice: 'Sourcetype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sourcetype
      @sourcetype = Sourcetype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sourcetype_params
      params.require(:sourcetype).permit(:sourcetype)
    end
end

app/helpers/sourcetypes_helper.rb
module SourcetypesHelper
end

app/views/sourcetypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sourcetypes</h1>

<table>
  <thead>
    <tr>
      <th>Sourcetype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sourcetypes.each do |sourcetype| %>
      <tr>
        <td><%= sourcetype.sourcetype %></td>
        <td><%= link_to 'Show', sourcetype %></td>
        <td><%= link_to 'Edit', edit_sourcetype_path(sourcetype) %></td>
        <td><%= link_to 'Destroy', sourcetype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sourcetypes/show.html.erb
<p>
  <strong>Sourcetype:</strong>
  <%= @sourcetype.sourcetype %>
</p>

<%= link_to 'Back', sourcetypes_path %>