config/routes.rb
  Rails.application.routes.draw do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    root :to => 'home#index'
    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    resources :preloadsources
    resources :sourcetypes
    resources :languages
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/preloadsource.rb
class Preloadsource < ApplicationRecord
    belongs_to :sourcetype
    belongs_to :language
    has_many :subscriptions, :dependent => :destroy
    has_many :users, through: :subscriptions
    
end

app/controllers/preloadsources_controller.rb
class PreloadsourcesController < ApplicationController
  before_action :set_preloadsource, only: [:show, :edit, :update, :destroy]

  # GET /preloadsources
  # GET /preloadsources.json
  def index
    @preloadsources = Preloadsource.all
  end

  # GET /preloadsources/1
  # GET /preloadsources/1.json
  def show
  end

  # GET /preloadsources/new
  def new
    @preloadsource = Preloadsource.new
  end

  # GET /preloadsources/1/edit
  def edit
  end

  # POST /preloadsources
  # POST /preloadsources.json
  def create
    @preloadsource = Preloadsource.new(preloadsource_params)

    respond_to do |format|
      if @preloadsource.save
        format.html { redirect_to @preloadsource, notice: 'Preloadsource was successfully created.' }
        format.json { render :show, status: :created, location: @preloadsource }
      else
        format.html { render :new }
        format.json { render json: @preloadsource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preloadsources/1
  # PATCH/PUT /preloadsources/1.json
  def update
    respond_to do |format|
      if @preloadsource.update(preloadsource_params)
        format.html { redirect_to @preloadsource, notice: 'Preloadsource was successfully updated.' }
        format.json { render :show, status: :ok, location: @preloadsource }
      else
        format.html { render :edit }
        format.json { render json: @preloadsource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preloadsources/1
  # DELETE /preloadsources/1.json
  def destroy
    @preloadsource.destroy
    respond_to do |format|
      format.html { redirect_to preloadsources_url, notice: 'Preloadsource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preloadsource
      @preloadsource = Preloadsource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preloadsource_params
      params.require(:preloadsource).permit(:preloadsourcename, :preloadsourceurl, :language_id, :sourcetype_id)
    end
end

app/helpers/preloadsources_helper.rb
module PreloadsourcesHelper
end

app/views/preloadsources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Preloadsources</h1>

<table>
  <thead>
    <tr>
      <th>Preloadsourcename</th>
      <th>Preloadsourceurl</th>
      <th>Language</th>
      <th>Sourcetype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preloadsources.each do |preloadsource| %>
      <tr>
        <td><%= preloadsource.preloadsourcename %></td>
        <td><%= preloadsource.preloadsourceurl %></td>
        <td><%= preloadsource.language_id %></td>
        <td><%= preloadsource.sourcetype_id %></td>
        <td><%= link_to 'Show', preloadsource %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/preloadsources/show.html.erb
<p>
  <strong>Preloadsourcename:</strong>
  <%= @preloadsource.preloadsourcename %>
</p>

<p>
  <strong>Preloadsourceurl:</strong>
  <%= @preloadsource.preloadsourceurl %>
</p>

<p>
  <strong>Language:</strong>
  <%= @preloadsource.language_id %>
</p>

<p>
  <strong>Sourcetype:</strong>
  <%= @preloadsource.sourcetype_id %>
</p>

<%= link_to 'Back', preloadsources_path %>